# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from panther.basic import future_pb2 as basic_dot_future__pb2
from panther.basic import option_pb2 as basic_dot_option__pb2
from panther.basic import stock_pb2 as basic_dot_stock__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in basic/basic_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BasicInterfaceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllStockDetail = channel.unary_unary(
                '/basic.BasicInterface/GetAllStockDetail',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=basic_dot_stock__pb2.StockDetailList.FromString,
                _registered_method=True)
        self.GetAllFutureDetail = channel.unary_unary(
                '/basic.BasicInterface/GetAllFutureDetail',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=basic_dot_future__pb2.FutureDetailList.FromString,
                _registered_method=True)
        self.GetAllOptionDetail = channel.unary_unary(
                '/basic.BasicInterface/GetAllOptionDetail',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=basic_dot_option__pb2.OptionDetailList.FromString,
                _registered_method=True)


class BasicInterfaceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllStockDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllFutureDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllOptionDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BasicInterfaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllStockDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllStockDetail,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=basic_dot_stock__pb2.StockDetailList.SerializeToString,
            ),
            'GetAllFutureDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllFutureDetail,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=basic_dot_future__pb2.FutureDetailList.SerializeToString,
            ),
            'GetAllOptionDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllOptionDetail,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=basic_dot_option__pb2.OptionDetailList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'basic.BasicInterface', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('basic.BasicInterface', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BasicInterface(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllStockDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/basic.BasicInterface/GetAllStockDetail',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            basic_dot_stock__pb2.StockDetailList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllFutureDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/basic.BasicInterface/GetAllFutureDetail',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            basic_dot_future__pb2.FutureDetailList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllOptionDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/basic.BasicInterface/GetAllOptionDetail',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            basic_dot_option__pb2.OptionDetailList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
