# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: basic/stock.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'basic/stock.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x62\x61sic/stock.proto\x12\x05\x62\x61sic\"\xea\x03\n\x0bStockDetail\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x11\n\tday_trade\x18\x04 \x01(\t\x12\x15\n\rdelivery_date\x18\x05 \x01(\t\x12\x16\n\x0e\x64\x65livery_month\x18\x06 \x01(\t\x12\x10\n\x08\x65xchange\x18\x07 \x01(\t\x12\x12\n\nlimit_down\x18\x08 \x01(\x01\x12\x10\n\x08limit_up\x18\t \x01(\x01\x12\x1e\n\x16margin_trading_balance\x18\n \x01(\x03\x12\x12\n\nmultiplier\x18\x0b \x01(\x03\x12\x0c\n\x04name\x18\x0c \x01(\t\x12\x14\n\x0coption_right\x18\r \x01(\t\x12\x11\n\treference\x18\x0e \x01(\x01\x12\x15\n\rsecurity_type\x18\x0f \x01(\t\x12\x1d\n\x15short_selling_balance\x18\x10 \x01(\x03\x12\x14\n\x0cstrike_price\x18\x11 \x01(\x03\x12\x0e\n\x06symbol\x18\x12 \x01(\t\x12\x13\n\x0btarget_code\x18\x13 \x01(\t\x12\x17\n\x0funderlying_code\x18\x14 \x01(\t\x12\x17\n\x0funderlying_kind\x18\x15 \x01(\t\x12\x0c\n\x04unit\x18\x16 \x01(\x03\x12\x13\n\x0bupdate_date\x18\x17 \x01(\t\"3\n\x0fStockDetailList\x12 \n\x04list\x18\x01 \x03(\x0b\x32\x12.basic.StockDetailB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'basic.stock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_STOCKDETAIL']._serialized_start=29
  _globals['_STOCKDETAIL']._serialized_end=519
  _globals['_STOCKDETAILLIST']._serialized_start=521
  _globals['_STOCKDETAILLIST']._serialized_end=572
# @@protoc_insertion_point(module_scope)
