# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from panther.stream import stream_pb2 as stream_dot_stream__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in stream/stream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StreamInterfaceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeShioajiEvent = channel.unary_stream(
                '/stream.StreamInterface/SubscribeShioajiEvent',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stream_dot_stream__pb2.ShioajiEvent.FromString,
                _registered_method=True)
        self.SubscribeFutureTick = channel.unary_stream(
                '/stream.StreamInterface/SubscribeFutureTick',
                request_serializer=stream_dot_stream__pb2.SubscribeFutureRequest.SerializeToString,
                response_deserializer=stream_dot_stream__pb2.FutureTick.FromString,
                _registered_method=True)
        self.SubscribeFutureBidAsk = channel.unary_stream(
                '/stream.StreamInterface/SubscribeFutureBidAsk',
                request_serializer=stream_dot_stream__pb2.SubscribeFutureRequest.SerializeToString,
                response_deserializer=stream_dot_stream__pb2.FutureBidAsk.FromString,
                _registered_method=True)


class StreamInterfaceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubscribeShioajiEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeFutureTick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeFutureBidAsk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamInterfaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeShioajiEvent': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeShioajiEvent,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stream_dot_stream__pb2.ShioajiEvent.SerializeToString,
            ),
            'SubscribeFutureTick': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeFutureTick,
                    request_deserializer=stream_dot_stream__pb2.SubscribeFutureRequest.FromString,
                    response_serializer=stream_dot_stream__pb2.FutureTick.SerializeToString,
            ),
            'SubscribeFutureBidAsk': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeFutureBidAsk,
                    request_deserializer=stream_dot_stream__pb2.SubscribeFutureRequest.FromString,
                    response_serializer=stream_dot_stream__pb2.FutureBidAsk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stream.StreamInterface', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stream.StreamInterface', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StreamInterface(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeShioajiEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/stream.StreamInterface/SubscribeShioajiEvent',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stream_dot_stream__pb2.ShioajiEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeFutureTick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/stream.StreamInterface/SubscribeFutureTick',
            stream_dot_stream__pb2.SubscribeFutureRequest.SerializeToString,
            stream_dot_stream__pb2.FutureTick.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeFutureBidAsk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/stream.StreamInterface/SubscribeFutureBidAsk',
            stream_dot_stream__pb2.SubscribeFutureRequest.SerializeToString,
            stream_dot_stream__pb2.FutureBidAsk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
