# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stream/stream.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'stream/stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13stream/stream.proto\x12\x06stream\"f\n\x0cShioajiEvent\x12\x11\n\tresp_code\x18\x01 \x01(\x03\x12\x12\n\nevent_code\x18\x02 \x01(\x03\x12\x0c\n\x04info\x18\x03 \x01(\t\x12\r\n\x05\x65vent\x18\x04 \x01(\t\x12\x12\n\nevent_time\x18\x05 \x01(\t\"*\n\x1aSubscribeFutureTickRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"\xf1\x02\n\nFutureTick\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x11\n\tdate_time\x18\x02 \x01(\t\x12\x0c\n\x04open\x18\x03 \x01(\x01\x12\x18\n\x10underlying_price\x18\x04 \x01(\x01\x12\x1a\n\x12\x62id_side_total_vol\x18\x05 \x01(\x03\x12\x1a\n\x12\x61sk_side_total_vol\x18\x06 \x01(\x03\x12\x11\n\tavg_price\x18\x07 \x01(\x01\x12\r\n\x05\x63lose\x18\x08 \x01(\x01\x12\x0c\n\x04high\x18\t \x01(\x01\x12\x0b\n\x03low\x18\n \x01(\x01\x12\x0e\n\x06\x61mount\x18\x0b \x01(\x01\x12\x14\n\x0ctotal_amount\x18\x0c \x01(\x01\x12\x0e\n\x06volume\x18\r \x01(\x03\x12\x14\n\x0ctotal_volume\x18\x0e \x01(\x03\x12\x11\n\ttick_type\x18\x0f \x01(\x03\x12\x10\n\x08\x63hg_type\x18\x10 \x01(\x03\x12\x11\n\tprice_chg\x18\x11 \x01(\x01\x12\x0f\n\x07pct_chg\x18\x12 \x01(\x01\x12\x10\n\x08simtrade\x18\x13 \x01(\x08\x32\x64\n\x0fStreamInterface\x12Q\n\x13SubscribeFutureTick\x12\".stream.SubscribeFutureTickRequest\x1a\x12.stream.FutureTick\"\x00\x30\x01\x42\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stream.stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_SHIOAJIEVENT']._serialized_start=31
  _globals['_SHIOAJIEVENT']._serialized_end=133
  _globals['_SUBSCRIBEFUTURETICKREQUEST']._serialized_start=135
  _globals['_SUBSCRIBEFUTURETICKREQUEST']._serialized_end=177
  _globals['_FUTURETICK']._serialized_start=180
  _globals['_FUTURETICK']._serialized_end=549
  _globals['_STREAMINTERFACE']._serialized_start=551
  _globals['_STREAMINTERFACE']._serialized_end=651
# @@protoc_insertion_point(module_scope)
