// @generated by protobuf-ts 2.11.0 with parameter use_proto_field_name,long_type_number,force_client_none,server_none
// @generated from protobuf file "basic/basic.proto" (package "basic", syntax proto3)
// tslint:disable
import { OptionDetailList } from "./option";
import { FutureDetailList } from "./future";
import { StockDetailList } from "./stock";
import { Empty } from "../google/protobuf/empty";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service basic.BasicDataInterface
 */
export const BasicDataInterface = new ServiceType("basic.BasicDataInterface", [
    { name: "GetAllStockDetail", options: {}, I: Empty, O: StockDetailList },
    { name: "GetAllFutureDetail", options: {}, I: Empty, O: FutureDetailList },
    { name: "GetAllOptionDetail", options: {}, I: Empty, O: OptionDetailList }
]);
