// @generated by protobuf-ts 2.11.0 with parameter use_proto_field_name,long_type_number,force_client_none,server_none
// @generated from protobuf file "basic/basic.proto" (package "basic", syntax proto3)
// tslint:disable
import { OptionDetail } from "./option";
import { FutureDetail } from "./future";
import { StockDetail } from "./stock";
import { Empty } from "../google/protobuf/empty";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service basic.BasicDataInterface
 */
export const BasicDataInterface = new ServiceType("basic.BasicDataInterface", [
    { name: "GetAllStockDetail", options: {}, I: Empty, O: StockDetail },
    { name: "GetAllFutureDetail", options: {}, I: Empty, O: FutureDetail },
    { name: "GetAllOptionDetail", options: {}, I: Empty, O: OptionDetail }
]);
