// @generated by protobuf-ts 2.11.1 with parameter use_proto_field_name,long_type_number,force_client_none,server_none
// @generated from protobuf file "health/health.proto" (package "health", syntax proto3)
// tslint:disable
import { Empty } from "../google/protobuf/empty";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service health.BasicDataInterface
 */
export const BasicDataInterface = new ServiceType("health.BasicDataInterface", [
    { name: "HealthChannel", serverStreaming: true, clientStreaming: true, options: {}, I: Empty, O: Empty }
]);
