// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: auth/auth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// class APISecret(BaseModel):
//
//	api_key: str
//	api_key_secret: str
type APISecret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ApiKeySecret  string                 `protobuf:"bytes,2,opt,name=api_key_secret,json=apiKeySecret,proto3" json:"api_key_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APISecret) Reset() {
	*x = APISecret{}
	mi := &file_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APISecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APISecret) ProtoMessage() {}

func (x *APISecret) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APISecret.ProtoReflect.Descriptor instead.
func (*APISecret) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *APISecret) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *APISecret) GetApiKeySecret() string {
	if x != nil {
		return x.ApiKeySecret
	}
	return ""
}

// class CASecret(BaseModel):
//
//	person_id: str
//	ca_path: str
//	ca_password: str
type CASecret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PersonId      string                 `protobuf:"bytes,1,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	CaPath        string                 `protobuf:"bytes,2,opt,name=ca_path,json=caPath,proto3" json:"ca_path,omitempty"`
	CaPassword    string                 `protobuf:"bytes,3,opt,name=ca_password,json=caPassword,proto3" json:"ca_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CASecret) Reset() {
	*x = CASecret{}
	mi := &file_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CASecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASecret) ProtoMessage() {}

func (x *CASecret) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASecret.ProtoReflect.Descriptor instead.
func (*CASecret) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *CASecret) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *CASecret) GetCaPath() string {
	if x != nil {
		return x.CaPath
	}
	return ""
}

func (x *CASecret) GetCaPassword() string {
	if x != nil {
		return x.CaPassword
	}
	return ""
}

// class ShioajiAuth(BaseModel):
//
//	name: str
//	api_secret: APISecret
//	ca_secret: CASecret
type ShioajiAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ApiSecret     *APISecret             `protobuf:"bytes,2,opt,name=api_secret,json=apiSecret,proto3" json:"api_secret,omitempty"`
	CaSecret      *CASecret              `protobuf:"bytes,3,opt,name=ca_secret,json=caSecret,proto3" json:"ca_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShioajiAuth) Reset() {
	*x = ShioajiAuth{}
	mi := &file_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShioajiAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShioajiAuth) ProtoMessage() {}

func (x *ShioajiAuth) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShioajiAuth.ProtoReflect.Descriptor instead.
func (*ShioajiAuth) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ShioajiAuth) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShioajiAuth) GetApiSecret() *APISecret {
	if x != nil {
		return x.ApiSecret
	}
	return nil
}

func (x *ShioajiAuth) GetCaSecret() *CASecret {
	if x != nil {
		return x.CaSecret
	}
	return nil
}

var File_auth_auth_proto protoreflect.FileDescriptor

const file_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x0fauth/auth.proto\x12\x04auth\"J\n" +
	"\tAPISecret\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12$\n" +
	"\x0eapi_key_secret\x18\x02 \x01(\tR\fapiKeySecret\"a\n" +
	"\bCASecret\x12\x1b\n" +
	"\tperson_id\x18\x01 \x01(\tR\bpersonId\x12\x17\n" +
	"\aca_path\x18\x02 \x01(\tR\x06caPath\x12\x1f\n" +
	"\vca_password\x18\x03 \x01(\tR\n" +
	"caPassword\"~\n" +
	"\vShioajiAuth\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\n" +
	"api_secret\x18\x02 \x01(\v2\x0f.auth.APISecretR\tapiSecret\x12+\n" +
	"\tca_secret\x18\x03 \x01(\v2\x0e.auth.CASecretR\bcaSecretB\x06Z\x04./pbb\x06proto3"

var (
	file_auth_auth_proto_rawDescOnce sync.Once
	file_auth_auth_proto_rawDescData []byte
)

func file_auth_auth_proto_rawDescGZIP() []byte {
	file_auth_auth_proto_rawDescOnce.Do(func() {
		file_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)))
	})
	return file_auth_auth_proto_rawDescData
}

var file_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_auth_auth_proto_goTypes = []any{
	(*APISecret)(nil),   // 0: auth.APISecret
	(*CASecret)(nil),    // 1: auth.CASecret
	(*ShioajiAuth)(nil), // 2: auth.ShioajiAuth
}
var file_auth_auth_proto_depIdxs = []int32{
	0, // 0: auth.ShioajiAuth.api_secret:type_name -> auth.APISecret
	1, // 1: auth.ShioajiAuth.ca_secret:type_name -> auth.CASecret
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_auth_auth_proto_init() }
func file_auth_auth_proto_init() {
	if File_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_auth_proto_goTypes,
		DependencyIndexes: file_auth_auth_proto_depIdxs,
		MessageInfos:      file_auth_auth_proto_msgTypes,
	}.Build()
	File_auth_auth_proto = out.File
	file_auth_auth_proto_goTypes = nil
	file_auth_auth_proto_depIdxs = nil
}
