// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: system/backup.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Backup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backup) Reset() {
	*x = Backup{}
	mi := &file_system_backup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backup) ProtoMessage() {}

func (x *Backup) ProtoReflect() protoreflect.Message {
	mi := &file_system_backup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backup.ProtoReflect.Descriptor instead.
func (*Backup) Descriptor() ([]byte, []int) {
	return file_system_backup_proto_rawDescGZIP(), []int{0}
}

func (x *Backup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Backup) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Backup) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type BackupList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Backup              `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupList) Reset() {
	*x = BackupList{}
	mi := &file_system_backup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupList) ProtoMessage() {}

func (x *BackupList) ProtoReflect() protoreflect.Message {
	mi := &file_system_backup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupList.ProtoReflect.Descriptor instead.
func (*BackupList) Descriptor() ([]byte, []int) {
	return file_system_backup_proto_rawDescGZIP(), []int{1}
}

func (x *BackupList) GetList() []*Backup {
	if x != nil {
		return x.List
	}
	return nil
}

var File_system_backup_proto protoreflect.FileDescriptor

const file_system_backup_proto_rawDesc = "" +
	"\n" +
	"\x13system/backup.proto\x12\x06system\x1a\x1fgoogle/protobuf/timestamp.proto\"k\n" +
	"\x06Backup\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"0\n" +
	"\n" +
	"BackupList\x12\"\n" +
	"\x04list\x18\x01 \x03(\v2\x0e.system.BackupR\x04listB\x06Z\x04./pbb\x06proto3"

var (
	file_system_backup_proto_rawDescOnce sync.Once
	file_system_backup_proto_rawDescData []byte
)

func file_system_backup_proto_rawDescGZIP() []byte {
	file_system_backup_proto_rawDescOnce.Do(func() {
		file_system_backup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_backup_proto_rawDesc), len(file_system_backup_proto_rawDesc)))
	})
	return file_system_backup_proto_rawDescData
}

var file_system_backup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_system_backup_proto_goTypes = []any{
	(*Backup)(nil),                // 0: system.Backup
	(*BackupList)(nil),            // 1: system.BackupList
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_system_backup_proto_depIdxs = []int32{
	2, // 0: system.Backup.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: system.BackupList.list:type_name -> system.Backup
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_system_backup_proto_init() }
func file_system_backup_proto_init() {
	if File_system_backup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_backup_proto_rawDesc), len(file_system_backup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_system_backup_proto_goTypes,
		DependencyIndexes: file_system_backup_proto_depIdxs,
		MessageInfos:      file_system_backup_proto_msgTypes,
	}.Build()
	File_system_backup_proto = out.File
	file_system_backup_proto_goTypes = nil
	file_system_backup_proto_depIdxs = nil
}
