// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: basic/basic.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_basic_basic_proto protoreflect.FileDescriptor

const file_basic_basic_proto_rawDesc = "" +
	"\n" +
	"\x11basic/basic.proto\x12\x05basic\x1a\x1bgoogle/protobuf/empty.proto\x1a\x11basic/stock.proto\x1a\x12basic/future.proto\x1a\x12basic/option.proto2\xe9\x01\n" +
	"\x0eBasicInterface\x12E\n" +
	"\x11GetAllStockDetail\x12\x16.google.protobuf.Empty\x1a\x16.basic.StockDetailList\"\x00\x12G\n" +
	"\x12GetAllFutureDetail\x12\x16.google.protobuf.Empty\x1a\x17.basic.FutureDetailList\"\x00\x12G\n" +
	"\x12GetAllOptionDetail\x12\x16.google.protobuf.Empty\x1a\x17.basic.OptionDetailList\"\x00B\x06Z\x04./pbb\x06proto3"

var file_basic_basic_proto_goTypes = []any{
	(*emptypb.Empty)(nil),    // 0: google.protobuf.Empty
	(*StockDetailList)(nil),  // 1: basic.StockDetailList
	(*FutureDetailList)(nil), // 2: basic.FutureDetailList
	(*OptionDetailList)(nil), // 3: basic.OptionDetailList
}
var file_basic_basic_proto_depIdxs = []int32{
	0, // 0: basic.BasicInterface.GetAllStockDetail:input_type -> google.protobuf.Empty
	0, // 1: basic.BasicInterface.GetAllFutureDetail:input_type -> google.protobuf.Empty
	0, // 2: basic.BasicInterface.GetAllOptionDetail:input_type -> google.protobuf.Empty
	1, // 3: basic.BasicInterface.GetAllStockDetail:output_type -> basic.StockDetailList
	2, // 4: basic.BasicInterface.GetAllFutureDetail:output_type -> basic.FutureDetailList
	3, // 5: basic.BasicInterface.GetAllOptionDetail:output_type -> basic.OptionDetailList
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_basic_basic_proto_init() }
func file_basic_basic_proto_init() {
	if File_basic_basic_proto != nil {
		return
	}
	file_basic_stock_proto_init()
	file_basic_future_proto_init()
	file_basic_option_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_basic_basic_proto_rawDesc), len(file_basic_basic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_basic_basic_proto_goTypes,
		DependencyIndexes: file_basic_basic_proto_depIdxs,
	}.Build()
	File_basic_basic_proto = out.File
	file_basic_basic_proto_goTypes = nil
	file_basic_basic_proto_depIdxs = nil
}
