// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: health/health.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HealthInterface_HealthChannel_FullMethodName = "/health.HealthInterface/HealthChannel"
)

// HealthInterfaceClient is the client API for HealthInterface service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthInterfaceClient interface {
	HealthChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[emptypb.Empty, emptypb.Empty], error)
}

type healthInterfaceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthInterfaceClient(cc grpc.ClientConnInterface) HealthInterfaceClient {
	return &healthInterfaceClient{cc}
}

func (c *healthInterfaceClient) HealthChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[emptypb.Empty, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HealthInterface_ServiceDesc.Streams[0], HealthInterface_HealthChannel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HealthInterface_HealthChannelClient = grpc.BidiStreamingClient[emptypb.Empty, emptypb.Empty]

// HealthInterfaceServer is the server API for HealthInterface service.
// All implementations must embed UnimplementedHealthInterfaceServer
// for forward compatibility.
type HealthInterfaceServer interface {
	HealthChannel(grpc.BidiStreamingServer[emptypb.Empty, emptypb.Empty]) error
	mustEmbedUnimplementedHealthInterfaceServer()
}

// UnimplementedHealthInterfaceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthInterfaceServer struct{}

func (UnimplementedHealthInterfaceServer) HealthChannel(grpc.BidiStreamingServer[emptypb.Empty, emptypb.Empty]) error {
	return status.Errorf(codes.Unimplemented, "method HealthChannel not implemented")
}
func (UnimplementedHealthInterfaceServer) mustEmbedUnimplementedHealthInterfaceServer() {}
func (UnimplementedHealthInterfaceServer) testEmbeddedByValue()                         {}

// UnsafeHealthInterfaceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthInterfaceServer will
// result in compilation errors.
type UnsafeHealthInterfaceServer interface {
	mustEmbedUnimplementedHealthInterfaceServer()
}

func RegisterHealthInterfaceServer(s grpc.ServiceRegistrar, srv HealthInterfaceServer) {
	// If the following call pancis, it indicates UnimplementedHealthInterfaceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthInterface_ServiceDesc, srv)
}

func _HealthInterface_HealthChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HealthInterfaceServer).HealthChannel(&grpc.GenericServerStream[emptypb.Empty, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HealthInterface_HealthChannelServer = grpc.BidiStreamingServer[emptypb.Empty, emptypb.Empty]

// HealthInterface_ServiceDesc is the grpc.ServiceDesc for HealthInterface service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthInterface_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "health.HealthInterface",
	HandlerType: (*HealthInterfaceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HealthChannel",
			Handler:       _HealthInterface_HealthChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "health/health.proto",
}
