// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: basic/stock.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//	{
//	    "category": "03",
//	    "code": "1321",
//	    "currency": "TWD",
//	    "day_trade": "Yes",
//	    "delivery_date": "",
//	    "delivery_month": "",
//	    "exchange": "TSE",
//	    "limit_down": 32.95,
//	    "limit_up": 40.25,
//	    "margin_trading_balance": 128,
//	    "multiplier": 0,
//	    "name": "\u5927\u6d0b",
//	    "option_right": "",
//	    "reference": 36.6,
//	    "security_type": "STK",
//	    "short_selling_balance": 45,
//	    "strike_price": 0,
//	    "symbol": "TSE1321",
//	    "target_code": "",
//	    "underlying_code": "",
//	    "underlying_kind": "",
//	    "unit": 1000,
//	    "update_date": "2025/06/13"
//	}
type StockDetail struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Category             string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Code                 string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Currency             string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	DayTrade             string                 `protobuf:"bytes,4,opt,name=day_trade,json=dayTrade,proto3" json:"day_trade,omitempty"`
	DeliveryDate         string                 `protobuf:"bytes,5,opt,name=delivery_date,json=deliveryDate,proto3" json:"delivery_date,omitempty"`
	DeliveryMonth        string                 `protobuf:"bytes,6,opt,name=delivery_month,json=deliveryMonth,proto3" json:"delivery_month,omitempty"`
	Exchange             string                 `protobuf:"bytes,7,opt,name=exchange,proto3" json:"exchange,omitempty"`
	LimitDown            float64                `protobuf:"fixed64,8,opt,name=limit_down,json=limitDown,proto3" json:"limit_down,omitempty"`
	LimitUp              float64                `protobuf:"fixed64,9,opt,name=limit_up,json=limitUp,proto3" json:"limit_up,omitempty"`
	MarginTradingBalance int64                  `protobuf:"varint,10,opt,name=margin_trading_balance,json=marginTradingBalance,proto3" json:"margin_trading_balance,omitempty"`
	Multiplier           int64                  `protobuf:"varint,11,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	Name                 string                 `protobuf:"bytes,12,opt,name=name,proto3" json:"name,omitempty"`
	OptionRight          string                 `protobuf:"bytes,13,opt,name=option_right,json=optionRight,proto3" json:"option_right,omitempty"`
	Reference            float64                `protobuf:"fixed64,14,opt,name=reference,proto3" json:"reference,omitempty"`
	SecurityType         string                 `protobuf:"bytes,15,opt,name=security_type,json=securityType,proto3" json:"security_type,omitempty"`
	ShortSellingBalance  int64                  `protobuf:"varint,16,opt,name=short_selling_balance,json=shortSellingBalance,proto3" json:"short_selling_balance,omitempty"`
	StrikePrice          int64                  `protobuf:"varint,17,opt,name=strike_price,json=strikePrice,proto3" json:"strike_price,omitempty"`
	Symbol               string                 `protobuf:"bytes,18,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TargetCode           string                 `protobuf:"bytes,19,opt,name=target_code,json=targetCode,proto3" json:"target_code,omitempty"`
	UnderlyingCode       string                 `protobuf:"bytes,20,opt,name=underlying_code,json=underlyingCode,proto3" json:"underlying_code,omitempty"`
	UnderlyingKind       string                 `protobuf:"bytes,21,opt,name=underlying_kind,json=underlyingKind,proto3" json:"underlying_kind,omitempty"`
	Unit                 int64                  `protobuf:"varint,22,opt,name=unit,proto3" json:"unit,omitempty"`
	UpdateDate           string                 `protobuf:"bytes,23,opt,name=update_date,json=updateDate,proto3" json:"update_date,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StockDetail) Reset() {
	*x = StockDetail{}
	mi := &file_basic_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockDetail) ProtoMessage() {}

func (x *StockDetail) ProtoReflect() protoreflect.Message {
	mi := &file_basic_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockDetail.ProtoReflect.Descriptor instead.
func (*StockDetail) Descriptor() ([]byte, []int) {
	return file_basic_stock_proto_rawDescGZIP(), []int{0}
}

func (x *StockDetail) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *StockDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StockDetail) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *StockDetail) GetDayTrade() string {
	if x != nil {
		return x.DayTrade
	}
	return ""
}

func (x *StockDetail) GetDeliveryDate() string {
	if x != nil {
		return x.DeliveryDate
	}
	return ""
}

func (x *StockDetail) GetDeliveryMonth() string {
	if x != nil {
		return x.DeliveryMonth
	}
	return ""
}

func (x *StockDetail) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *StockDetail) GetLimitDown() float64 {
	if x != nil {
		return x.LimitDown
	}
	return 0
}

func (x *StockDetail) GetLimitUp() float64 {
	if x != nil {
		return x.LimitUp
	}
	return 0
}

func (x *StockDetail) GetMarginTradingBalance() int64 {
	if x != nil {
		return x.MarginTradingBalance
	}
	return 0
}

func (x *StockDetail) GetMultiplier() int64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *StockDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StockDetail) GetOptionRight() string {
	if x != nil {
		return x.OptionRight
	}
	return ""
}

func (x *StockDetail) GetReference() float64 {
	if x != nil {
		return x.Reference
	}
	return 0
}

func (x *StockDetail) GetSecurityType() string {
	if x != nil {
		return x.SecurityType
	}
	return ""
}

func (x *StockDetail) GetShortSellingBalance() int64 {
	if x != nil {
		return x.ShortSellingBalance
	}
	return 0
}

func (x *StockDetail) GetStrikePrice() int64 {
	if x != nil {
		return x.StrikePrice
	}
	return 0
}

func (x *StockDetail) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StockDetail) GetTargetCode() string {
	if x != nil {
		return x.TargetCode
	}
	return ""
}

func (x *StockDetail) GetUnderlyingCode() string {
	if x != nil {
		return x.UnderlyingCode
	}
	return ""
}

func (x *StockDetail) GetUnderlyingKind() string {
	if x != nil {
		return x.UnderlyingKind
	}
	return ""
}

func (x *StockDetail) GetUnit() int64 {
	if x != nil {
		return x.Unit
	}
	return 0
}

func (x *StockDetail) GetUpdateDate() string {
	if x != nil {
		return x.UpdateDate
	}
	return ""
}

type StockDetailList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*StockDetail         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockDetailList) Reset() {
	*x = StockDetailList{}
	mi := &file_basic_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockDetailList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockDetailList) ProtoMessage() {}

func (x *StockDetailList) ProtoReflect() protoreflect.Message {
	mi := &file_basic_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockDetailList.ProtoReflect.Descriptor instead.
func (*StockDetailList) Descriptor() ([]byte, []int) {
	return file_basic_stock_proto_rawDescGZIP(), []int{1}
}

func (x *StockDetailList) GetList() []*StockDetail {
	if x != nil {
		return x.List
	}
	return nil
}

var File_basic_stock_proto protoreflect.FileDescriptor

const file_basic_stock_proto_rawDesc = "" +
	"\n" +
	"\x11basic/stock.proto\x12\x05basic\"\xff\x05\n" +
	"\vStockDetail\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x1b\n" +
	"\tday_trade\x18\x04 \x01(\tR\bdayTrade\x12#\n" +
	"\rdelivery_date\x18\x05 \x01(\tR\fdeliveryDate\x12%\n" +
	"\x0edelivery_month\x18\x06 \x01(\tR\rdeliveryMonth\x12\x1a\n" +
	"\bexchange\x18\a \x01(\tR\bexchange\x12\x1d\n" +
	"\n" +
	"limit_down\x18\b \x01(\x01R\tlimitDown\x12\x19\n" +
	"\blimit_up\x18\t \x01(\x01R\alimitUp\x124\n" +
	"\x16margin_trading_balance\x18\n" +
	" \x01(\x03R\x14marginTradingBalance\x12\x1e\n" +
	"\n" +
	"multiplier\x18\v \x01(\x03R\n" +
	"multiplier\x12\x12\n" +
	"\x04name\x18\f \x01(\tR\x04name\x12!\n" +
	"\foption_right\x18\r \x01(\tR\voptionRight\x12\x1c\n" +
	"\treference\x18\x0e \x01(\x01R\treference\x12#\n" +
	"\rsecurity_type\x18\x0f \x01(\tR\fsecurityType\x122\n" +
	"\x15short_selling_balance\x18\x10 \x01(\x03R\x13shortSellingBalance\x12!\n" +
	"\fstrike_price\x18\x11 \x01(\x03R\vstrikePrice\x12\x16\n" +
	"\x06symbol\x18\x12 \x01(\tR\x06symbol\x12\x1f\n" +
	"\vtarget_code\x18\x13 \x01(\tR\n" +
	"targetCode\x12'\n" +
	"\x0funderlying_code\x18\x14 \x01(\tR\x0eunderlyingCode\x12'\n" +
	"\x0funderlying_kind\x18\x15 \x01(\tR\x0eunderlyingKind\x12\x12\n" +
	"\x04unit\x18\x16 \x01(\x03R\x04unit\x12\x1f\n" +
	"\vupdate_date\x18\x17 \x01(\tR\n" +
	"updateDate\"9\n" +
	"\x0fStockDetailList\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.basic.StockDetailR\x04listB\x06Z\x04./pbb\x06proto3"

var (
	file_basic_stock_proto_rawDescOnce sync.Once
	file_basic_stock_proto_rawDescData []byte
)

func file_basic_stock_proto_rawDescGZIP() []byte {
	file_basic_stock_proto_rawDescOnce.Do(func() {
		file_basic_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_basic_stock_proto_rawDesc), len(file_basic_stock_proto_rawDesc)))
	})
	return file_basic_stock_proto_rawDescData
}

var file_basic_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_basic_stock_proto_goTypes = []any{
	(*StockDetail)(nil),     // 0: basic.StockDetail
	(*StockDetailList)(nil), // 1: basic.StockDetailList
}
var file_basic_stock_proto_depIdxs = []int32{
	0, // 0: basic.StockDetailList.list:type_name -> basic.StockDetail
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_basic_stock_proto_init() }
func file_basic_stock_proto_init() {
	if File_basic_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_basic_stock_proto_rawDesc), len(file_basic_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_basic_stock_proto_goTypes,
		DependencyIndexes: file_basic_stock_proto_depIdxs,
		MessageInfos:      file_basic_stock_proto_msgTypes,
	}.Build()
	File_basic_stock_proto = out.File
	file_basic_stock_proto_goTypes = nil
	file_basic_stock_proto_depIdxs = nil
}
