// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: system/system.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemBuild struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Commit        string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemBuild) Reset() {
	*x = SystemBuild{}
	mi := &file_system_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemBuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemBuild) ProtoMessage() {}

func (x *SystemBuild) ProtoReflect() protoreflect.Message {
	mi := &file_system_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemBuild.ProtoReflect.Descriptor instead.
func (*SystemBuild) Descriptor() ([]byte, []int) {
	return file_system_system_proto_rawDescGZIP(), []int{0}
}

func (x *SystemBuild) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SystemBuild) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

type SystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LaunchTime    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=launch_time,json=launchTime,proto3" json:"launch_time,omitempty"`
	DiskUsage     float64                `protobuf:"fixed64,2,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	Core          *SystemBuild           `protobuf:"bytes,3,opt,name=core,proto3" json:"core,omitempty"`
	Web           *SystemBuild           `protobuf:"bytes,4,opt,name=web,proto3" json:"web,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_system_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_system_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_system_system_proto_rawDescGZIP(), []int{1}
}

func (x *SystemInfo) GetLaunchTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LaunchTime
	}
	return nil
}

func (x *SystemInfo) GetDiskUsage() float64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *SystemInfo) GetCore() *SystemBuild {
	if x != nil {
		return x.Core
	}
	return nil
}

func (x *SystemInfo) GetWeb() *SystemBuild {
	if x != nil {
		return x.Web
	}
	return nil
}

var File_system_system_proto protoreflect.FileDescriptor

const file_system_system_proto_rawDesc = "" +
	"\n" +
	"\x13system/system.proto\x12\x06system\x1a\x1fgoogle/protobuf/timestamp.proto\"?\n" +
	"\vSystemBuild\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\"\xb8\x01\n" +
	"\n" +
	"SystemInfo\x12;\n" +
	"\vlaunch_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"launchTime\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\x02 \x01(\x01R\tdiskUsage\x12'\n" +
	"\x04core\x18\x03 \x01(\v2\x13.system.SystemBuildR\x04core\x12%\n" +
	"\x03web\x18\x04 \x01(\v2\x13.system.SystemBuildR\x03webB\x06Z\x04./pbb\x06proto3"

var (
	file_system_system_proto_rawDescOnce sync.Once
	file_system_system_proto_rawDescData []byte
)

func file_system_system_proto_rawDescGZIP() []byte {
	file_system_system_proto_rawDescOnce.Do(func() {
		file_system_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_system_proto_rawDesc), len(file_system_system_proto_rawDesc)))
	})
	return file_system_system_proto_rawDescData
}

var file_system_system_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_system_system_proto_goTypes = []any{
	(*SystemBuild)(nil),           // 0: system.SystemBuild
	(*SystemInfo)(nil),            // 1: system.SystemInfo
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_system_system_proto_depIdxs = []int32{
	2, // 0: system.SystemInfo.launch_time:type_name -> google.protobuf.Timestamp
	0, // 1: system.SystemInfo.core:type_name -> system.SystemBuild
	0, // 2: system.SystemInfo.web:type_name -> system.SystemBuild
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_system_system_proto_init() }
func file_system_system_proto_init() {
	if File_system_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_system_proto_rawDesc), len(file_system_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_system_system_proto_goTypes,
		DependencyIndexes: file_system_system_proto_depIdxs,
		MessageInfos:      file_system_system_proto_msgTypes,
	}.Build()
	File_system_system_proto = out.File
	file_system_system_proto_goTypes = nil
	file_system_system_proto_depIdxs = nil
}
