// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: system/user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRole int32

const (
	UserRole_UNKNOWN UserRole = 0
	UserRole_USER    UserRole = 1
	UserRole_ADMIN   UserRole = 2
	UserRole_ROOT    UserRole = 3
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "UNKNOWN",
		1: "USER",
		2: "ADMIN",
		3: "ROOT",
	}
	UserRole_value = map[string]int32{
		"UNKNOWN": 0,
		"USER":    1,
		"ADMIN":   2,
		"ROOT":    3,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_system_user_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_system_user_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_system_user_proto_rawDescGZIP(), []int{0}
}

type BasicUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Role          UserRole               `protobuf:"varint,4,opt,name=role,proto3,enum=system.UserRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicUser) Reset() {
	*x = BasicUser{}
	mi := &file_system_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicUser) ProtoMessage() {}

func (x *BasicUser) ProtoReflect() protoreflect.Message {
	mi := &file_system_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicUser.ProtoReflect.Descriptor instead.
func (*BasicUser) Descriptor() ([]byte, []int) {
	return file_system_user_proto_rawDescGZIP(), []int{0}
}

func (x *BasicUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BasicUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BasicUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *BasicUser) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_UNKNOWN
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Basic         *BasicUser             `protobuf:"bytes,2,opt,name=basic,proto3" json:"basic,omitempty"`
	EnableTotp    bool                   `protobuf:"varint,3,opt,name=enable_totp,json=enableTotp,proto3" json:"enable_totp,omitempty"`
	TotpId        int64                  `protobuf:"varint,4,opt,name=totp_id,json=totpId,proto3" json:"totp_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,31,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,32,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_system_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_system_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_system_user_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetBasic() *BasicUser {
	if x != nil {
		return x.Basic
	}
	return nil
}

func (x *User) GetEnableTotp() bool {
	if x != nil {
		return x.EnableTotp
	}
	return false
}

func (x *User) GetTotpId() int64 {
	if x != nil {
		return x.TotpId
	}
	return 0
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*User                `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserList) Reset() {
	*x = UserList{}
	mi := &file_system_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList) ProtoMessage() {}

func (x *UserList) ProtoReflect() protoreflect.Message {
	mi := &file_system_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList.ProtoReflect.Descriptor instead.
func (*UserList) Descriptor() ([]byte, []int) {
	return file_system_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserList) GetList() []*User {
	if x != nil {
		return x.List
	}
	return nil
}

type Totp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	QrCode        string                 `protobuf:"bytes,3,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Totp) Reset() {
	*x = Totp{}
	mi := &file_system_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Totp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Totp) ProtoMessage() {}

func (x *Totp) ProtoReflect() protoreflect.Message {
	mi := &file_system_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Totp.ProtoReflect.Descriptor instead.
func (*Totp) Descriptor() ([]byte, []int) {
	return file_system_user_proto_rawDescGZIP(), []int{3}
}

func (x *Totp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Totp) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Totp) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

var File_system_user_proto protoreflect.FileDescriptor

const file_system_user_proto_rawDesc = "" +
	"\n" +
	"\x11system/user.proto\x12\x06system\x1a\x1fgoogle/protobuf/timestamp.proto\"\x7f\n" +
	"\tBasicUser\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12$\n" +
	"\x04role\x18\x04 \x01(\x0e2\x10.system.UserRoleR\x04role\"\xef\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12'\n" +
	"\x05basic\x18\x02 \x01(\v2\x11.system.BasicUserR\x05basic\x12\x1f\n" +
	"\venable_totp\x18\x03 \x01(\bR\n" +
	"enableTotp\x12\x17\n" +
	"\atotp_id\x18\x04 \x01(\x03R\x06totpId\x129\n" +
	"\n" +
	"created_at\x18\x1f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18  \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\",\n" +
	"\bUserList\x12 \n" +
	"\x04list\x18\x01 \x03(\v2\f.system.UserR\x04list\"G\n" +
	"\x04Totp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x17\n" +
	"\aqr_code\x18\x03 \x01(\tR\x06qrCode*6\n" +
	"\bUserRole\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04USER\x10\x01\x12\t\n" +
	"\x05ADMIN\x10\x02\x12\b\n" +
	"\x04ROOT\x10\x03B\x06Z\x04./pbb\x06proto3"

var (
	file_system_user_proto_rawDescOnce sync.Once
	file_system_user_proto_rawDescData []byte
)

func file_system_user_proto_rawDescGZIP() []byte {
	file_system_user_proto_rawDescOnce.Do(func() {
		file_system_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_user_proto_rawDesc), len(file_system_user_proto_rawDesc)))
	})
	return file_system_user_proto_rawDescData
}

var file_system_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_system_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_system_user_proto_goTypes = []any{
	(UserRole)(0),                 // 0: system.UserRole
	(*BasicUser)(nil),             // 1: system.BasicUser
	(*User)(nil),                  // 2: system.User
	(*UserList)(nil),              // 3: system.UserList
	(*Totp)(nil),                  // 4: system.Totp
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_system_user_proto_depIdxs = []int32{
	0, // 0: system.BasicUser.role:type_name -> system.UserRole
	1, // 1: system.User.basic:type_name -> system.BasicUser
	5, // 2: system.User.created_at:type_name -> google.protobuf.Timestamp
	5, // 3: system.User.updated_at:type_name -> google.protobuf.Timestamp
	2, // 4: system.UserList.list:type_name -> system.User
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_system_user_proto_init() }
func file_system_user_proto_init() {
	if File_system_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_user_proto_rawDesc), len(file_system_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_system_user_proto_goTypes,
		DependencyIndexes: file_system_user_proto_depIdxs,
		EnumInfos:         file_system_user_proto_enumTypes,
		MessageInfos:      file_system_user_proto_msgTypes,
	}.Build()
	File_system_user_proto = out.File
	file_system_user_proto_goTypes = nil
	file_system_user_proto_depIdxs = nil
}
