// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: system/user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BasicUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicUser) Reset() {
	*x = BasicUser{}
	mi := &file_system_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicUser) ProtoMessage() {}

func (x *BasicUser) ProtoReflect() protoreflect.Message {
	mi := &file_system_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicUser.ProtoReflect.Descriptor instead.
func (*BasicUser) Descriptor() ([]byte, []int) {
	return file_system_user_proto_rawDescGZIP(), []int{0}
}

func (x *BasicUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BasicUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BasicUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LocalUser struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Basic              *BasicUser             `protobuf:"bytes,2,opt,name=basic,proto3" json:"basic,omitempty"`
	NeedChangePassword bool                   `protobuf:"varint,3,opt,name=need_change_password,json=needChangePassword,proto3" json:"need_change_password,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,31,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,32,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LocalUser) Reset() {
	*x = LocalUser{}
	mi := &file_system_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalUser) ProtoMessage() {}

func (x *LocalUser) ProtoReflect() protoreflect.Message {
	mi := &file_system_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalUser.ProtoReflect.Descriptor instead.
func (*LocalUser) Descriptor() ([]byte, []int) {
	return file_system_user_proto_rawDescGZIP(), []int{1}
}

func (x *LocalUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LocalUser) GetBasic() *BasicUser {
	if x != nil {
		return x.Basic
	}
	return nil
}

func (x *LocalUser) GetNeedChangePassword() bool {
	if x != nil {
		return x.NeedChangePassword
	}
	return false
}

func (x *LocalUser) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *LocalUser) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type LocalUserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*LocalUser           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalUserList) Reset() {
	*x = LocalUserList{}
	mi := &file_system_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalUserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalUserList) ProtoMessage() {}

func (x *LocalUserList) ProtoReflect() protoreflect.Message {
	mi := &file_system_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalUserList.ProtoReflect.Descriptor instead.
func (*LocalUserList) Descriptor() ([]byte, []int) {
	return file_system_user_proto_rawDescGZIP(), []int{2}
}

func (x *LocalUserList) GetList() []*LocalUser {
	if x != nil {
		return x.List
	}
	return nil
}

type Totp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	QrCode        string                 `protobuf:"bytes,3,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Totp) Reset() {
	*x = Totp{}
	mi := &file_system_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Totp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Totp) ProtoMessage() {}

func (x *Totp) ProtoReflect() protoreflect.Message {
	mi := &file_system_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Totp.ProtoReflect.Descriptor instead.
func (*Totp) Descriptor() ([]byte, []int) {
	return file_system_user_proto_rawDescGZIP(), []int{3}
}

func (x *Totp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Totp) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Totp) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

var File_system_user_proto protoreflect.FileDescriptor

const file_system_user_proto_rawDesc = "" +
	"\n" +
	"\x11system/user.proto\x12\x06system\x1a\x1fgoogle/protobuf/timestamp.proto\"Y\n" +
	"\tBasicUser\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\xec\x01\n" +
	"\tLocalUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12'\n" +
	"\x05basic\x18\x02 \x01(\v2\x11.system.BasicUserR\x05basic\x120\n" +
	"\x14need_change_password\x18\x03 \x01(\bR\x12needChangePassword\x129\n" +
	"\n" +
	"created_at\x18\x1f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18  \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"6\n" +
	"\rLocalUserList\x12%\n" +
	"\x04list\x18\x01 \x03(\v2\x11.system.LocalUserR\x04list\"G\n" +
	"\x04Totp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x17\n" +
	"\aqr_code\x18\x03 \x01(\tR\x06qrCodeB\x06Z\x04./pbb\x06proto3"

var (
	file_system_user_proto_rawDescOnce sync.Once
	file_system_user_proto_rawDescData []byte
)

func file_system_user_proto_rawDescGZIP() []byte {
	file_system_user_proto_rawDescOnce.Do(func() {
		file_system_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_user_proto_rawDesc), len(file_system_user_proto_rawDesc)))
	})
	return file_system_user_proto_rawDescData
}

var file_system_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_system_user_proto_goTypes = []any{
	(*BasicUser)(nil),             // 0: system.BasicUser
	(*LocalUser)(nil),             // 1: system.LocalUser
	(*LocalUserList)(nil),         // 2: system.LocalUserList
	(*Totp)(nil),                  // 3: system.Totp
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_system_user_proto_depIdxs = []int32{
	0, // 0: system.LocalUser.basic:type_name -> system.BasicUser
	4, // 1: system.LocalUser.created_at:type_name -> google.protobuf.Timestamp
	4, // 2: system.LocalUser.updated_at:type_name -> google.protobuf.Timestamp
	1, // 3: system.LocalUserList.list:type_name -> system.LocalUser
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_system_user_proto_init() }
func file_system_user_proto_init() {
	if File_system_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_user_proto_rawDesc), len(file_system_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_system_user_proto_goTypes,
		DependencyIndexes: file_system_user_proto_depIdxs,
		MessageInfos:      file_system_user_proto_msgTypes,
	}.Build()
	File_system_user_proto = out.File
	file_system_user_proto_goTypes = nil
	file_system_user_proto_depIdxs = nil
}
