# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/auth.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'auth/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61uth/auth.proto\x12\x04\x61uth\"4\n\tAPISecret\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\x12\x16\n\x0e\x61pi_key_secret\x18\x02 \x01(\t\"C\n\x08\x43\x41Secret\x12\x11\n\tperson_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x61_path\x18\x02 \x01(\t\x12\x13\n\x0b\x63\x61_password\x18\x03 \x01(\t\"c\n\x0bShioajiAuth\x12\x0c\n\x04name\x18\x01 \x01(\t\x12#\n\napi_secret\x18\x02 \x01(\x0b\x32\x0f.auth.APISecret\x12!\n\tca_secret\x18\x03 \x01(\x0b\x32\x0e.auth.CASecretB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_APISECRET']._serialized_start=25
  _globals['_APISECRET']._serialized_end=77
  _globals['_CASECRET']._serialized_start=79
  _globals['_CASECRET']._serialized_end=146
  _globals['_SHIOAJIAUTH']._serialized_start=148
  _globals['_SHIOAJIAUTH']._serialized_end=247
# @@protoc_insertion_point(module_scope)
